"""followers

Revision ID: 836997674275
Revises: 077d647d7515
Create Date: 2020-09-26 13:44:39.251175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '836997674275'
down_revision = '077d647d7515'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
